install:
  - pip install --user boto3

script:
  - # openssl aes-256-cbc -K $encrypted_745b33c0c930_key -iv $encrypted_745b33c0c930_iv -in id_rsa.enc -out id_rsa -d
  - # chmod 0600 id_rsa
  - # export GIT_SSH_COMMAND='ssh -i '`pwd`'/id_rsa'
  - git clone https://github.com/raboof/testwiki source
  - mkdir target
  - ./generate.sh
  - ls -alFh target

deploy:
  provider: script
  script: ./deploy.py
#  script: git add .; git commit -m "Wiki software update"; git push
  skip_cleanup: true

env:
  global:
    - SOURCE=source
    - TARGET=target
    - POST_URL="https://g6l6tkgusl.execute-api.eu-west-1.amazonaws.com/sw_prod"
    - AWS_ACCESS_KEY_ID="AKIAIDSMELSBUXLZJY2Q"
    - AWS_DEFAULT_REGION="eu-west-1"
    - secure: "MTS6+Y711u0il4mhggcdbce5B8MOaGW9VeZl3QrNvyEcwyCPwVZe4tJUezqEdnw2fuLPsifApw/0HjE5y774IcrvbUZ/YiEzyrpj2eCHNdKjYqHH4K+8L1T3dIIocOp4dTSMNtIJazrlN4BNb1QWIgGIvgW9fDawprNXwai4sqwl1i1cNBLh8eoVTG6HR3sknFmWkzotPUoZcTsWziWInVaohjaVyTzIAsGjTPYWXTcDIaF95hyRxgmVoN+frM8ZByCam7e2RqWEfO8NKX3ILz+P4NVbK/HiHWGko4evukUqXbNgIYBLSXho9gBN41rHV32f1Qt2HYLkHitI9AGM7ZhqGL26JlqNsbMCto6w9DevtDwg8766P9aTAZiEXo0vsTxfMJX3K8cIO1oPbHbyMCC06/m+xvonUFnfdyruvbkxMNq550Kua2JrEGUQ0oGxfglcNtv2IENxAzvv6WvaegcIi4VshP63ELOft7GyugyMkQZZ97jz5NC7FoPW2qTIIvYf5g36paR8/9YOZekojSG3H0W+LJw3h3zDdHCSWoBVlRs0F03OZLQ9aaIUrH+M5GkiK4q+oWEIoHVMw1FFuwL1O9AX5vSB4I89hMaRYKiUdHkdqwT1xnCfThr3Av7wfrGWAq7D5aaQm3mtvucRFc/9ZycUXHzN9Bl2+UL4ijM="
